### ISSUE TITLE
Fix URL next to description of the project

### ISSUE THREAD

**Issue by tripu** [w3c/speech-api#2]
I guess the &ldquo;website&rdquo; field that is shown on the front page of the repo, at the top, should be either
`https://w3c.github.io/speech-api/webspeechapi.html`
or
`https://w3c.github.io/speech-api/speechapi.html`
?

**Comment by foolip** [comment]
Yeah, I used the URL that I think we should use, hoping nobody would notice until we have something there. I'll fix it and change it back later.
