### ISSUE TITLE
Convert to Bikeshed

### ISSUE THREAD

**Issue by foolip** [w3c/speech-api#3]
https://github.com/tabatkins/bikeshed is used for most modern specs.

**Comment by foolip** [comment]
In https://github.com/whatwg/fullscreen/issues/47 I converted Fullscreen to Bikeshed, and there are a number of scripts you can run to check if the output is still similar enough to the original. https://github.com/foolip/epubbase/blob/master/worddiff.py is one, the others a snippets of JS somewhere on the Fullscreen issue/PR/branch.

**Comment by foolip** [comment]
@andrenatal, any progress on this?

**Comment by andrenatal** [comment]
I'll start working on this later this week @foolip
