### ISSUE TITLE
Implement travis-ci to run tests and deploy automatically 

### ISSUE THREAD

**Issue by andrenatal** [w3c/speech-api#5]

**Comment by foolip** [comment]
There are some good clues about how to set this up in https://github.com/whatwg/dom/pull/350

**Comment by foolip** [comment]
There are scripts in https://github.com/WICG/mediasession that you might steal.

**Comment by foolip** [comment]
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd is a better guide.
