### ISSUE TITLE
Update spec to new IDL syntax for optional dictionaries

### ISSUE THREAD

**Issue by Ms2ger** [w3c/speech-api#60]
See heycam/webidl#758

**Comment by marcoscaceres** [comment]
ReSpec will automatically fix this in next release.

**Comment by foolip** [comment]
This spec uses Bikeshed :)

**Comment by foolip** [comment]
There also aren't any optional dictionaries in the spec AFAICT. @Ms2ger?

**Comment by Ms2ger** [comment]
They're optional in Gecko, but apparently not (anymore) in the spec. (I hope there's tests for that.)

**Comment by marcoscaceres** [comment]
Ah, my bad. Nm.

**Comment by foolip** [comment]
Yep, tested:
https://github.com/web-platform-tests/wpt/blob/master/speech-api/SpeechSynthesisEvent-constructor.html
https://github.com/web-platform-tests/wpt/blob/master/speech-api/SpeechSynthesisErrorEvent-constructor.html
