### ISSUE TITLE
Is SpeechSynthesisUtterance reusable?

### ISSUE THREAD

**Issue by makotokato** [w3c/speech-api#7]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1372325#c14

Sample is the following.
```javascript
var utter = new SpeechSynthesisUtterance("Hello World");
utter.onend = () => {
  // Edge, WebKit and Blink allow this, but Firefox doesn't.
  window.speechSynthesis.speak(utter);
};
window.speechSynthesis.speak(utter);
```

Google search page uses that `SpeechSynthesisUtterance` is reused.  But Speech API doesn't define whether this object is reusable.

Edge, WebKit, and Blink allow `SpeechSynthesisUtterance` is reusable now, but Gecko doesn't.  If it allow to reuse this object, we should add spec/document about reusable.

**Comment by foolip** [comment]
@gshires, do you have thoughts on this?

**Comment by foolip** [comment]
@gshires poked @minorninth :)

**Comment by karlcow** [comment]
@foolip and we had a Webcompat issue about it. 
https://github.com/webcompat/web-bugs/issues/2966

**Comment by minorninth** [comment]
I don't have a really strong preference for whether it should be reusable or not, but I agree that we should come to a consensus and document it.

Is there any reason NOT to allow SpeechSynthesisUtterance to be reused? If not, let's file a bug against Gecko to allow it to be reused, and if they accept it, we can document it and then we'll have parity.

**Comment by karlcow** [comment]
@minorninth 

>If not, let's file a bug against Gecko to allow it to be reused, and if they accept it, we can document it and then we'll have parity.

This is the origin of this issue. 😄 In the first description, the link is there.
https://bugzilla.mozilla.org/show_bug.cgi?id=1372325

**Comment by karlcow** [comment]
+1 to allow the reuse of it.

* Edge, Chrome and Safari do the same thing
* Google search is using the feature.

**Comment by foolip** [comment]
Sounds like we should absolutely fix this. The problematic bit in the spec is "The SpeechSynthesis object takes exclusive ownership of the SpeechSynthesisUtterance object. Passing it as a speak() argument to another SpeechSynthesis object should throw an exception."

Is it just a matter of removing this, or does that open up new and hard questions to answer?

**Comment by foolip** [comment]
Does anyone know who the best contacts for Edge and Safari would be for Speech? In https://github.com/w3c/web-platform-tests/pull/7507 I'm adding OWNERS and would like to include them, and https://github.com/w3c/web-platform-tests/pull/7510 will fail in Safari, so their input would be great.

@patrickkettner @youennf halp?

**Comment by eeejay** [comment]
>  The problematic bit in the spec is "The SpeechSynthesis object takes exclusive ownership of the SpeechSynthesisUtterance object. Passing it as a speak() argument to another SpeechSynthesis object should throw an exception."

How does this relate to re-usability with the same SpeechSynthesis instance? Seems like that sentence could stay with a qualifier that re-using an utterance in the same SpeechSynthesis instance is OK.

**Comment by foolip** [comment]
Oh, I actually hadn't read that very carefully, what it says is actually quite reasonable. Then we should just have a test to prove that it throws when passing to another window's SpeechSynthesis instance.

**Comment by patrickkettner** [comment]
@foolip I'll track down the right person for you on the edge side of stuff

**Comment by foolip** [comment]
Thanks @patrickkettner, can you add them to https://github.com/w3c/web-platform-tests/blob/master/speech-api/OWNERS if you find them?

@makotokato, with the added test, I think this issue is resolved, WDYT?

**Comment by makotokato** [comment]
> with the added test, I think this issue is resolved, WDYT?

Yes, as this issue, it is OK.
